### ISSUE TITLE
README.md is not finished

### ISSUE THREAD

**Issue by CheezBallzPi** [RoboEagles4828/Landroval#1]
Someone help me finish the README.md tutorial. Pls?

**Comment by CheezBallzPi** [comment]
@alebcay @P1n3appl3 Halp plis

**Comment by alebcay** [comment]
Well, I didn't see this until now since you didn't ping me. Like this, @CheezBallzPi.

**Comment by CheezBallzPi** [comment]
Oh, my bad...

Next time I'll remember T.T

Pls help tho...

@RoboEagles4828/senior-programmers

**Comment by CheezBallzPi** [comment]
Close #1
